# Generated by Django 5.2.6 on 2025-09-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('checking', 'Checking'), ('analysis', 'Analysis'), ('archived', 'Archived'), ('failed', 'Failed'), ('pending', 'Praduate'), ('success', 'Success')], default='checking', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
