# Generated by Django 5.2.6 on 2025-11-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('checking', 'Checking'), ('analysis', 'Analysis'), ('archived', 'Archived'), ('failed', 'Failed'), ('pending', 'Pending'), ('success', 'Success')], default='checking', max_length=64),
        ),
    ]
