# Generated by Django 5.2.6 on 2026-01-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainha', '0004_standard_standardrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardrule',
            name='group',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
