# Generated by Django 5.2.6 on 2026-01-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainha', '0005_alter_standardrule_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('checking', 'Checking'), ('analysis', 'Analysis'), ('archived', 'Archived'), ('failed', 'Failed'), ('pending', 'Pending'), ('approved', 'Approved')], default='checking', max_length=64),
        ),
    ]
