# Generated by Django 5.2.6 on 2026-02-11 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainha', '0006_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('analysis', 'Analysis'), ('failed', 'Failed'), ('pending', 'Pending'), ('approved', 'Approved')], default='analysis', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainha.project')),
                ('standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainha.standard')),
            ],
        ),
    ]
