# Generated by Django 5.2.6 on 2026-02-18 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainha', '0007_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfilled', models.BooleanField(default=None, null=True)),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainha.standardrule')),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainha.validation')),
            ],
        ),
    ]
