# Generated by Django 5.2.6 on 2026-03-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainha', '0009_validation_analyzed_validation_analyzed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('cnpj', models.CharField(default=None, max_length=512, null=True)),
                ('email', models.CharField(default=None, max_length=512, null=True)),
                ('phone', models.CharField(default=None, max_length=512, null=True)),
                ('active', models.BooleanField(default=True)),
                ('subscription', models.CharField(choices=[('trial', 'trial'), ('basic', 'basic'), ('intermediate', 'intermediate'), ('advanced', 'advanced'), ('customized', 'customized')], default='trial', max_length=512)),
                ('payment_status', models.CharField(choices=[('free', 'free'), ('awaiting_payment', 'awaiting_payment'), ('paid', 'paid'), ('not_paid', 'not_paid'), ('expired', 'expired')], default='free', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
