# Generated by Django 5.2.6 on 2026-04-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainha', '0013_alter_account_email_alter_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cnpj',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
