# Generated by Django 5.2.6 on 2026-05-17 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainha', '0015_remove_project_user_project_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user'),
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.UniqueConstraint(fields=('user', 'account'), name='unique_user_in_account'),
        ),
    ]
