# Generated by Django 5.2.6 on 2026-05-19 16:30

import django.core.validators
import mainha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainha', '0016_useraccount_unique_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=mainha.models.project_file_dir_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'ifc'])]),
        ),
    ]
